steps:
  - label: "CUDA.jl"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.8
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command: |
      julia -e 'using Pkg

                println("--- :julia: Instantiating project")
                Pkg.develop(; path=pwd())
                Pkg.develop(; name="CUDA")

                println("+++ :julia: Running tests")
                Pkg.test("CUDA"; coverage=true)'
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 120

  - label: "oneAPI.jl"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.8
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command: |
      julia -e 'using Pkg;

                println("--- :julia: Instantiating project")
                Pkg.develop(; path=pwd())
                Pkg.develop(; name="oneAPI")

                println("+++ :julia: Building support library")
                include(joinpath(Pkg.devdir(), "oneAPI", "deps", "build_ci.jl"))
                Pkg.activate()

                println("+++ :julia: Running tests")
                Pkg.test("oneAPI"; coverage=true)'
    agents:
      queue: "juliagpu"
      intel: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60

  - label: "Metal.jl"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.8
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command: |
      julia -e 'using Pkg;

                println("--- :julia: Instantiating project")
                Pkg.develop(; path=pwd())
                Pkg.develop(; name="Metal")

                println("+++ :julia: Building support library")
                include(joinpath(Pkg.devdir(), "Metal", "deps", "build_ci.jl"))
                Pkg.activate()

                println("+++ :julia: Running tests")
                Pkg.test("Metal"; coverage=true)'
    agents:
      queue: "juliagpu"
      metal: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60

env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  SECRET_CODECOV_TOKEN: "GrevHmzmr2Vt6UK4wbbTTB1+kcMcIlF6nCXVCk3Z0plHDimpD6BwdN9T2A+5J9k3I2em0xXUqpt+2qUSqM8Bn5mNdpjR0TvxVY3oYXc+qzvBXmcZJpuCgJeoTP1P+kVFwszUn4na3fohNq9Qffp6tXMn/j8yJQKOiiC8mkD0aPEI0zISHuDaa/7j7JYf0vTrMRRZ9BMUQHmFuVaIQN8FLGG2BiE3236rj4eHh0lj2IfekCG3wd/LUzAsMx0MC3kIR8WzOWW2rf6xUMPkjm5+NuHwhAOcZc0+LRM7GYIwoW/nHAgyIqjvLiInNFmaJk+7V/GAKtd+gSAIzmyBUHAy6A==;U2FsdGVkX1+4ZljneQoaNE295nRIx8D6+WoFIgT6Pg2BXHaTyhTL4sxEcG0jX0e7oq68uvi4bK7x7YMS4L0Kew=="
